name = "audio-streamer"
main = "src/index.js"
compatibility_date = "2024-04-19"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "shortshorts-audio-prod"

[vars]
R2_ACCOUNT_ID = "dfd11ff2f8b18eab632465275938c6ac"
R2_BUCKET = "shortshorts-audio-prod"
