import type { Prisma } from "@prisma/client";

export const seedBooks: Prisma.BookCreateManyInput[] = [
  {
    id: "free-tell-tale-heart",
    gutenbergId: "2148",
    title: "The Tell-Tale Heart",
    author: "Edgar Allan Poe",
    narrator: "Elias Mercer",
    genre: "Gothic Horror",
    description:
      "A fevered confession from a man determined to prove his sanity after a murder and the creeping rhythm that follows him into the dark.",
    durationSeconds: 710,
    coverImageKey: "books/2148/audio/cover.jpg",
    audioKey: "books/2148/audio/Edgar_Allan_Poe.The_Tell-Tale_Heart.mp3",
    isFree: true,
    status: "pending",
  },
  {
    id: "free-gift-of-the-magi",
    gutenbergId: "7256",
    title: "The Gift of the Magi",
    author: "O. Henry",
    narrator: "Clara Wren",
    genre: "Holiday / Irony",
    description:
      "Two lovers with very little money make impossible choices to buy each other the perfect Christmas gift.",
    durationSeconds: 314,
    coverImageKey: "books/7256/audio/cover.jpg",
    audioKey: "books/7256/audio/O._Henry.The_Gift_of_the_Magi.mp3",
    isFree: true,
    status: "pending",
  },
  {
    id: "free-the-necklace",
    gutenbergId: "19555",
    title: "The Necklace",
    author: "Guy de Maupassant",
    narrator: "Juliette Vale",
    genre: "Realism",
    description:
      "A borrowed diamond necklace opens the door to one glamorous night and a decade of ruin. With cold precision, Maupassant dissects vanity, longing, and the quiet cruelty of circumstance — a masterpiece of ironic Realism.",
    durationSeconds: 6975,
    coverImageKey: "books/19555/audio/cover.jpg",
    audioKey: "books/19555/audio/Guy_de_Maupassant.The_Diamond_Necklace.mp3",
    isFree: true,
    status: "ready",
  },
  {
    id: "free-the-monkeys-paw",
    gutenbergId: "62129",
    title: "The Monkeys Paw",
    author: "W.W. Jacobs",
    narrator: "Rowan Pike",
    genre: "Supernatural Horror",
    description:
      "An ordinary family is offered three wishes and discovers the cost hidden inside every answered desire.",
    durationSeconds: 329,
    coverImageKey: "books/62129/audio/cover.jpg",
    audioKey: "books/62129/audio/W.W._Jacobs.The_Monkeys_Paw.mp3",
    isFree: true,
    status: "pending",
  },
  {
    id: "free-the-last-question",
    gutenbergId: "47875",
    title: "The Last Question",
    author: "Isaac Asimov",
    narrator: "Jonah Pierce",
    genre: "Hard Sci-Fi / Cosmic",
    description:
      "Across vast ages of human history, one question returns again and again as intelligence confronts entropy and the end of everything.",
    durationSeconds: 342,
    coverImageKey: "books/47875/audio/cover.jpg",
    audioKey: "books/47875/audio/Isaac_Asimov.The_Last_Question.mp3",
    isFree: true,
    status: "pending",
  },
  {
    id: "premium-the-yellow-wallpaper",
    gutenbergId: "1952",
    title: "The Yellow Wallpaper",
    author: "Charlotte Perkins Gilman",
    narrator: "Mara Ellison",
    genre: "Psychological Horror",
    description:
      "Confined to a quiet room to recover, a woman begins to read a terrible life into the wallpaper that surrounds her.",
    durationSeconds: 1260,
    coverImageKey: "books/1952/audio/cover.jpg",
    audioKey: "books/1952/audio/Charlotte_Perkins_Gilman.The_Yellow_Wallpaper.mp3",
    isFree: false,
    status: "ready",
  },
  {
    id: "premium-the-open-window",
    gutenbergId: "38369",
    title: "The Open Window",
    author: "Saki",
    narrator: "Miles Arden",
    genre: "Satire / Dark Humor",
    description:
      "A polished social visit unravels when a young storyteller invents a tragedy with perfectly timed confidence.",
    durationSeconds: 548,
    coverImageKey: "books/38369/audio/cover.jpg",
    audioKey: "books/38369/audio/Saki.The_Open_Window.mp3",
    isFree: false,
    status: "pending",
  },
  {
    id: "premium-occurrence-at-owl-creek",
    gutenbergId: "375",
    title: "An Occurrence at Owl Creek Bridge",
    author: "Ambrose Bierce",
    narrator: "Simon Welles",
    genre: "Psychological Thriller",
    description:
      "A condemned man imagines one last impossible escape in the suspended instant before death.",
    durationSeconds: 1188,
    coverImageKey: "books/375/audio/cover.jpg",
    audioKey: "books/375/audio/Ambrose_Bierce.An_Occurrence_at_Owl_Creek_Bridge.mp3",
    isFree: false,
    status: "pending",
  },
  {
    id: "premium-the-machine-stops",
    gutenbergId: "47394",
    title: "The Machine Stops",
    author: "E.M. Forster",
    narrator: "Silas Vale",
    genre: "Sci-Fi",
    description:
      "In a world where every need is handled by a global machine, one son insists that humanity cannot remain underground forever.",
    durationSeconds: 2460,
    coverImageKey: "books/47394/audio/cover.jpg",
    audioKey: "books/47394/audio/E.M._Forster.The_Machine_Stops.mp3",
    isFree: false,
    status: "pending",
  },
];

export const freeShelfIds = seedBooks.filter((book) => book.isFree).map((book) => book.id);
